version: "3"
services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./certs:/etc/nginx/certs
      - ./htpasswd:/etc/nginx/htpasswd
      - ./conf.d:/etc/nginx/conf.d
      - ./proxy.conf:/etc/nginx/proxy.conf
    restart: always
    networks:
      - front

networks:
  front:
    external:
      name: front
